### PR TITLE
Shortlink

### PR DESCRIPTION
**Pull request by Mobilpadde**
And a bit rewriting

### CODE REVIEW

**Comment by dragma** [comment]
Awesome !!!
Can you also update the README ?

**Comment by Mobilpadde** [comment]
Will do!

**Comment by Mobilpadde** [comment]
@dragma Done! Could use a push now 🥇

**Comment by dragma** [comment]
Thanks a lot. 
Will publish this on tomorow. ;)

**Comment by Mobilpadde** [comment]
Perfect!

**Comment by dragma** [comment]
I can't make it work. 
Can you open a PR with a demo code ? :)

EDIT: forget it. I managed to do it. This is more a server module and it has nothing to do with react. We must try to do something so it will.

**Comment by dragma** [comment]
I reverted the PR, waiting for changes.

**Comment by Mobilpadde** [comment]
It's a server module? Why is it called `react-coinhive`, if it has nothing to do with react? 🤙 

**Edit:** Just figured what you meant 🥉 

**Edit 2:** I have an idea for something else, will do it later today or tomorrow 💃

**Pull request merged**
